name: Test-auto-doc-generation

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
        sudo pip install pycodestyle
        pip install pdoc3
    - name: Add folders to Python Path
      run: |
          echo "PYTHONPATH=backend" >> $GITHUB_ENV
    - name: Auto Generate Documentation
      run: |
        echo "PYTHONPATH=./backend" >> $GITHUB_ENV
        pdoc --html backend --force --output-dir docs
        echo "Github reference"
        echo ${{ github.ref }}
        git add .
        git config --local user.name "auto generate docs"
        git config --local user.email "actions@github.com"
        git diff-index --quiet HEAD || git commit -m "CI: Automated build push" -a
    - name: Push Documentation
      if: github.ref == 'refs/heads/main'     - name: CodeCov
      if: startsWith(github.ref, 'refs/heads/main') || startsWith(github.ref, 'refs/heads/release-')
      uses: codecov/codecov-action@v3

      uses: ad-m/github-push-action@master
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: CodeCov
      uses: codecov/codecov-action@v3

