name: Test-style-checker
#Inactive as Autopep8 checker is used 
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
        sudo pip install pycodestyle
    - name: Add folders to Python Path
      run: |
          echo "PYTHONPATH=backend" >> $GITHUB_ENV
    - name: Style checkers
      run: |
        echo "PYTHONPATH=./backend" >> $GITHUB_ENV
        pycodestyle --first backend/app.py
    - name: CodeCov
      uses: codecov/codecov-action@v3
